# Generated by Django 5.1 on 2026-06-17 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='会員ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
                ('name', models.CharField(max_length=128, verbose_name='名前')),
                ('address', models.CharField(max_length=256, verbose_name='住所')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='管理者ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'administrator_admin',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='カテゴリID')),
                ('name', models.CharField(max_length=256, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'shopping_category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='メーカー名')),
                ('color', models.CharField(max_length=16, verbose_name='商品の色')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('recommended', models.BooleanField(default=False, verbose_name='オススメ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.category', verbose_name='カテゴリID')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='Itemincart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.item', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.account', verbose_name='会員ID')),
            ],
            options={
                'db_table': 'shopping_itemsincart',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文ID')),
                ('destination', models.CharField(max_length=256, verbose_name='配送先')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='注文日')),
                ('cancel', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.account', verbose_name='注文者')),
            ],
            options={
                'db_table': 'shopping_purchase',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=36, verbose_name='決済取引ID')),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='カード下4桁')),
                ('amount', models.IntegerField(verbose_name='決済金額')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='通貨')),
                ('status', models.CharField(default='succeeded', max_length=16, verbose_name='決済状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='決済日時')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ec_system.purchase', verbose_name='注文ID')),
            ],
            options={
                'db_table': 'shopping_payment',
            },
        ),
        migrations.CreateModel(
            name='Purchasedetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文詳細ID')),
                ('amount', models.IntegerField(verbose_name='注文数')),
                ('unit_price', models.IntegerField(default=0)),
                ('discount_rate', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.item', verbose_name='商品ID')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.purchase', verbose_name='注文ID')),
            ],
            options={
                'db_table': 'shopping_purchasedetail',
            },
        ),
        migrations.CreateModel(
            name='TimeSale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_rate', models.IntegerField()),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.item')),
            ],
        ),
    ]
