# Generated by Django 4.2.7 on 2026-06-16 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='会員ID'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='管理者ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='カテゴリID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='オススメ'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='キャンセル'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='注文ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.account', verbose_name='注文者'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase_detail_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='注文詳細ID'),
        ),
    ]
