# Generated by Django 5.1 on 2026-06-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
