# Generated by Django 5.1 on 2026-06-17 05:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_system', '0002_alter_account_user_id_alter_admin_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TimeSale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_rate', models.IntegerField()),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec_system.item')),
            ],
        ),
    ]
