# Generated by Django 5.1 on 2026-06-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_system', '0002_account_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='earned_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='use_point',
            field=models.IntegerField(default=0),
        ),
    ]
