# Generated by Django 5.1 on 2026-06-17 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_system', '0002_alter_account_user_id_alter_admin_admin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=36, verbose_name='決済取引ID')),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='カード下4桁')),
                ('amount', models.IntegerField(verbose_name='決済金額')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='通貨')),
                ('status', models.CharField(default='succeeded', max_length=16, verbose_name='決済状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='決済日時')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ec_system.purchase', verbose_name='注文ID')),
            ],
            options={
                'db_table': 'shopping_payment',
            },
        ),
    ]
